version: '2'

services:
  zookeeper:
    image: dearmai/kafka:v3.2.1
    ports:
      - "2181:2181"
    environment:
      - USE_ZOOKEEPER=true
      - KAFKA_OPTS=-Djava.security.auth.login.config=file:/app/kafka/config/zookeeper-jaas.properties
    volumes:
      - ./resources/zookeeper-jaas.properties:/app/kafka/config/zookeeper-jaas.properties
    restart: unless-stopped

  kafka:
    image: dearmai/kafka:v3.2.1
    ports:
      - "9092"
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=file:/app/kafka/config/kafka-jaas.properties
    volumes:
      - ./resources/server.properties:/app/kafka/config/server.properties
      - ./resources/kafka-jaas.properties:/app/kafka/config/kafka-jaas.properties
    restart: unless-stopped