version: '2'

services:
  zookeeper:
    image: dearmai/kafka:v3.2.1
#    build: ./docker
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - USE_ZOOKEEPER=true
      # - ZOOKEEPER_SASL_ENABLED=false
      # - KAFKA_OPTS=-Djava.security.auth.login.config=file:/app/kafka/config/zookeeper-jaas.properties
    volumes:
      # - ./resources/zookeeper-jaas.properties:/app/kafka/config/zookeeper-jaas.properties
      - ./resources/zookeeper.properties:/app/kafka/config/zookeeper.properties
    restart: unless-stopped

  kafka:
    image: dearmai/kafka:v3.2.1
#    build: ./docker
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=file:/app/kafka/config/kafka-jaas.properties
      # - KAFKA_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      # - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      # - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    volumes:
      - ./resources/server.properties:/app/kafka/config/server.properties
      - ./resources/kafka-jaas.properties:/app/kafka/config/kafka-jaas.properties
    restart: unless-stopped